pipeline {
    agent any

    environment {
        APP_NAME = "cloudlab-manager"
        BACKEND_DIR = "CloudLab-Manager/backend"
        FRONTEND_DIR = "CloudLab-Manager/frontend"
        DOCKERHUB_USER = "aryan13tech"
        DOCKERHUB_BACKEND = "cloudlab-backend"
        DOCKERHUB_FRONTEND = "cloudlab-frontend"
    }

    stages {

        stage('Pull Code From GitHub') {
            steps {
                echo "Pulling latest project code..."
                checkout scm
            }
        }

        stage('Cleanup Old Containers') {
            steps {
                sh '''
                echo "Stopping old Docker containers..."
                docker stop cloudlab_backend || true
                docker stop cloudlab_frontend || true

                echo "Removing old Docker containers..."
                docker rm cloudlab_backend || true
                docker rm cloudlab_frontend || true
                '''
            }
        }

        stage('Build Docker Images') {
    steps {
        sh '''
        echo "Building backend image..."
        docker build -t $DOCKERHUB_USER/$DOCKERHUB_BACKEND:latest "$BACKEND_DIR/Docker"

        echo "Building frontend image..."
        docker build -t $DOCKERHUB_USER/$DOCKERHUB_FRONTEND:latest "$FRONTEND_DIR/Docker"
        '''
    }
}


        stage('Login to DockerHub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    sh '''
                    echo "Logging into DockerHub..."
                    echo "$PASS" | docker login -u "$USER" --password-stdin
                    '''
                }
            }
        }

        stage('Push Images to DockerHub') {
            steps {
                sh '''
                echo "Pushing backend image..."
                docker push $DOCKERHUB_USER/$DOCKERHUB_BACKEND:latest

                echo "Pushing frontend image..."
                docker push $DOCKERHUB_USER/$DOCKERHUB_FRONTEND:latest
                '''
            }
        }

        stage('Deploy Containers') {
            steps {
                sh '''
                echo "Starting backend container..."
                docker run -d --name cloudlab_backend -p 8000:8000 $DOCKERHUB_USER/$DOCKERHUB_BACKEND:latest

                echo "Starting frontend container..."
                docker run -d --name cloudlab_frontend -p 80:80 $DOCKERHUB_USER/$DOCKERHUB_FRONTEND:latest
                '''
            }
        }
    }

    post {
        success {
            echo "CloudLab Manager Deployment Successful!"
        }
        failure {
            echo "Deployment Failed — Check Jenkins logs."
        }
    }
}
